// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEjyEMpd0ONRjPQNe5_O36p56Bvox8kaQ',
    appId: '1:160916278201:android:d8533606306714aaecc468',
    messagingSenderId: '160916278201',
    projectId: 'charcha-82500',
    storageBucket: 'charcha-82500.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfFamLn8Y4n2maNY1foEWudOHavMlc7FQ',
    appId: '1:160916278201:ios:b3c6f17f012304b5ecc468',
    messagingSenderId: '160916278201',
    projectId: 'charcha-82500',
    storageBucket: 'charcha-82500.firebasestorage.app',
    androidClientId: '160916278201-poj7u9pkckos4id9tjs4g2ki5qcc3mn9.apps.googleusercontent.com',
    iosClientId: '160916278201-dl70143kkob43c90nco7n26fkkhs3qnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.noobChat',
  );
}
